apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-worker
  namespace: kubesleuth-lab
  labels: {app: report-worker}
spec:
  replicas: 1
  selector:
    matchLabels: {app: report-worker}
  template:
    metadata:
      labels: {app: report-worker}
    spec:
      containers:
        - name: worker
          image: polinux/stress
          command: ["stress"]
          args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
          resources:
            requests: {memory: 32Mi}
            limits: {memory: 64Mi}
