apiVersion: v1
kind: Service
metadata:
  name: kumoshindan
  labels:
    app.kubernetes.io/name: kumoshindan
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kumoshindan
  ports:
    - name: http
      port: 8000
      targetPort: http
