apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: kumoshindan-lab
  labels: {app: web-frontend}
spec:
  replicas: 1
  selector:
    matchLabels: {app: web-frontend}
  template:
    metadata:
      labels: {app: web-frontend}
    spec:
      containers:
        - name: web
          image: nginx:1.27
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: kumoshindan-lab
spec:
  selector:
    app: web-front        # typo: should be web-frontend
  ports:
    - port: 80
      targetPort: 80
