alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "null"
      group_by: ["alertname", "namespace"]
      group_wait: 10s
      group_interval: 1m
      repeat_interval: 12h
      routes:
        - receiver: kumoshindan
          matchers:
            - 'namespace="kumoshindan-lab"'
    receivers:
      - name: "null"
      - name: kumoshindan
        webhook_configs:
          - url: http://kumoshindan.kumoshindan.svc.cluster.local:8000/webhook/alertmanager
            send_resolved: false
