apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-web
  namespace: kubesleuth-lab
  labels: {app: payments-web}
spec:
  replicas: 1
  selector:
    matchLabels: {app: payments-web}
  template:
    metadata:
      labels: {app: payments-web}
    spec:
      containers:
        - name: web
          image: nginx:1.99.99-doesnotexist
