apiVersion: v1
kind: Service
metadata:
  name: kubesleuth
  labels:
    app.kubernetes.io/name: kubesleuth
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kubesleuth
  ports:
    - name: http
      port: 8000
      targetPort: http
